name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '16.x' # Especifica a versão do Node.js
          check-latest: true # Verifica se há a última versão disponível
          cache: 'npm' # Define o gerenciador de pacotes que será cacheado
          cache-dependency-path: 'package-lock.json' # Arquivo para dependências

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

